### ISSUE TITLE
网络权重

### ISSUE THREAD

**Issue by Wuhuddy** [ZhengPeng7/GCoNet_plus#10]
您好，我从您google drive下载的权重包中用 （**ultimate_duts_cocoseg (The best one).pth**）评估，但和论文中还略微有点差距，且这个权重和（**ultimate_duts_cocoseg.pth**）应该是同一个，是上传错误了吗？

**Comment by ZhengPeng7** [comment]
嗨, 那您的performance是多少呢?

我记得应该就是这个权重文件, 他俩确实就是同一个, 只是标注明显一点而已.

那您有没有用过比如`ultimate_duts.pth`测一下看看和文中一不一致呢? 如果DUTS训的权重也和论文里的不一致, 那应该不是我传错了, 而是其他问题比如环境配置不一致导致结果不同.

**Comment by Wuhuddy** [comment]
![image](https://github.com/ZhengPeng7/GCoNet_plus/assets/121659356/e59aeb05-3ee9-44b4-b4a2-fc679000b860)
第一个为best，第二个为duts跑出的结果，都与论文中不同。我再尝试一下您的环境配置，感谢回复~

**Comment by ZhengPeng7** [comment]
没事, 不用客气.
我README里面有提供colab一整套直接一键run的test+evaluation的, 你可以试一下.
我刚刚也用它跑了下`ultimate_duts_cocoseg (The best one).pth on CoCA`的结果, 略有极小出入(Emax还比论文里的高了不到0.001)但是基本一致: 
> torch==1.13.1:
<img width="601" alt="截屏2023-10-09 18 26 55" src="https://github.com/ZhengPeng7/GCoNet_plus/assets/25921713/5b052c27-0fbf-4141-ae61-656474c5affb">

> torch==2.0.0:
<img width="549" alt="截屏2023-10-09 18 39 54" src="https://github.com/ZhengPeng7/GCoNet_plus/assets/25921713/bd63b605-67b4-4e93-9afb-a9083d1fee57">

所以应该是你那里有一点小问题.

**Comment by Wuhuddy** [comment]
感谢您，我也尝试了。
我还有另外的问题，我想在推理阶段生成DUTS和COCO-seg的预测图，中途显存为什么会爆掉呢？

**Comment by ZhengPeng7** [comment]
这个我不清楚啊, 毕竟colab上16G的T4也能跑.

**Comment by Wuhuddy** [comment]
您好，我又在colab上尝试了几次，推理时生成coco-seg的预测图还是会出现out of memory，应该也不是梯度未清零的原因吧

**Comment by Wuhuddy** [comment]
您好，我已经解决了，原因是推理时数据加载方式和训练时不同

**Comment by ZhengPeng7** [comment]
> 您好，我又在colab上尝试了几次，推理时生成coco-seg的预测图还是会出现out of memory，应该也不是梯度未清零的原因吧

哦对, 我想起来了... 因为inference时是默认加载整个group的. 而coco-seg的不同组的图像数量分布夸张得不均匀, 比如person这一group, 直接就几个G, 那你全读入去处理, 显存肯定是放不下的. 你换成正常的测试集就肯定没问题的.

**Comment by ZhengPeng7** [comment]
> 您好，我已经解决了，原因是推理时数据加载方式和训练时不同

哈哈, 好吧, 弄明白就好. 有问题欢迎继续留issue.

**Comment by Wuhuddy** [comment]
是的，感谢您的及时回复，非常感谢~
