### ISSUE TITLE
一些与sort_results.py和select_resulets.py相关的问题

### ISSUE THREAD

**Issue by IceHowe** [ZhengPeng7/GCoNet_plus#3]
![image](https://user-images.githubusercontent.com/35068131/182602576-3aec4ce8-36cc-4d9d-a5c7-18da2295a0c3.png)
您好，在运行sort_results.py和select_resulets.py时各有一个错误，第二个错误可能是因为第一个引起的，还没有看，对于第一个错误，我看到是来源于130行这句代码
![image](https://user-images.githubusercontent.com/35068131/182603052-693fdbfb-ae19-4d81-9924-89f7d31be7be.png)
其中best_ckpt的值为'gconet_-ep315:'，在130行代码中它取了一个空值，错误原因应该是在这
![image](https://user-images.githubusercontent.com/35068131/182604054-fb0e35c8-d815-4e26-ad02-117911dbe887.png)
请问trail这个变量原本应该是取什么值的？原本以为是取数字，但是后面的ep变量取的是数字315

**Comment by ZhengPeng7** [comment]
对的, 你命名一下就好, 比如gconet_TRIAL-ep315. 我之前就是跑实验的时候, 把用的方法/组合写作这个TRIAL, 就方便查看管理. `select_results.py`主要是挑一些质量高的结果图的,  修改一点单独运行也可以.

**Comment by IceHowe** [comment]
> 对的, 你命名一下就好, 比如gconet_TRIAL-ep315. 我之前就是跑实验的时候, 把用的方法/组合写作这个TRIAL, 就方便查看管理. `select_results.py`主要是挑一些质量高的结果图的, 修改一点单独运行也可以.

就是随便一个名字都行是吧？好的，感谢解答

**Comment by ZhengPeng7** [comment]
嗯, 没错. 这个项目有的地方写得还不是太好.

**Comment by IceHowe** [comment]
> 嗯, 没错. 这个项目有的地方写得还不是太好.

十分感谢，写了别的运行下去后发现是当前方法预测结果文件夹的名字

**Comment by ZhengPeng7** [comment]
嗯, 再有问题欢迎留言.

**Comment by IceHowe** [comment]
> 嗯, 再有问题欢迎留言.

嗯嗯
