### ISSUE TITLE
所提供的代码和训练命令训练时是默认使用了DUTS class和COCO-SEG吗

### ISSUE THREAD

**Issue by IceHowe** [ZhengPeng7/GCoNet_plus#4]
所提供的代码和训练命令训练时是默认使用了DUTS class和COCO-SEG吗？我看到在参数上只写了DUTS_class
![image](https://user-images.githubusercontent.com/35068131/184593847-3903caa2-df0f-4a48-a336-b31a28b71006.png)
```bash
CUDA_VISIBLE_DEVICES=0 python train.py --trainset DUTS_class --size ${size} --ckpt_dir ckpt/${method} --epochs ${epochs} --val_dir tmp4val_${method}
```

但是我在训练脚本里看到的是对两个训练集都遍历了
![image](https://user-images.githubusercontent.com/35068131/184594517-d2874754-522b-4b2b-b413-f2e6d01b22b5.png)
还有他的训练方式是训练一个batch的DUTS，然后一个bach的COCO-SEG，再更新梯度，是这样吗？

**Comment by ZhengPeng7** [comment]
嗯, 是的.
用了DUTS_class+COCO-SEG两个数据集.
优化时是两个分别计算, loss叠加起来, 一次backward的.

**Comment by IceHowe** [comment]
好的，了解了，感谢

**Comment by IceHowe** [comment]
请问没有多GPU运行代码是吗？那个sub by id脚本是不是多次运行的，而不是多GPU一起训练的

**Comment by ZhengPeng7** [comment]
对的, 那个是之前在dgx服务器上, 把一个setting跑多次的, 并不是多卡哈.

**Comment by YujieMo** [comment]
> 嗯, 是的. 用了DUTS_class+COCO-SEG两个数据集. 优化时是两个分别计算, loss叠加起来, 一次backward的.

您好，请问那为什么在论文中 Training Set的描述那里写的是"We follow the GICD [14] to use DUTS class
as our training set to design the experiments"，即只使用DUTS作为训练集呢？

**Comment by ZhengPeng7** [comment]
我们的所有的模块、实验设计都是仅使用DUTS_class的, 只是在得到所有的已经确定下来的一切(模型设计, 训练策略)后, 在最后使用了所有的已有training sets的组合训练了一下而已. 也就是说其实我们的一些超参的设置也并未针对DUTS_class+COCO-SEG, 而依然是DUTS_class.

**Comment by YujieMo** [comment]
> 我们的所有的模块、实验设计都是仅使用DUTS_class的, 只是在得到所有的已经确定下来的一切(模型设计, 训练策略)后, 在最后使用了所有的已有training sets的组合训练了一下而已. 也就是说其实我们的一些超参的设置也并未针对DUTS_class+COCO-SEG, 而依然是DUTS_class.

感谢您的即时回复，也就是说即使我在代码中只使用DUTS_class进行训练，也可以达到论文中理想的效果对吗

**Comment by ZhengPeng7** [comment]
不同训练集的结果可见于[此](https://github.com/ZhengPeng7/GCoNet_plus#result). 例如, 仅用DUTS_class训练就是仅用DUTS_class的performance (CoCA的Emax可达0.786). 还有问题欢迎继续留言哈.

**Comment by YujieMo** [comment]
> 不同训练集的结果可见于[此](https://github.com/ZhengPeng7/GCoNet_plus#result). 例如, 仅用DUTS_class训练就是仅用DUTS_class的performance (CoCA的Emax可达0.786). 还有问题欢迎继续留言哈.

好的，十分感谢您的回复

**Comment by zhiwang98** [comment]
你的cocoseg数据格式是怎么处理的，我记得cocoseg数据集还包括一个npy文件

**Comment by IceHowe** [comment]
> 你的cocoseg数据格式是怎么处理的，我记得cocoseg数据集还包括一个npy文件

我印象里没有你所说的文件，好像是直接下载就能用的，你可能下错了？

**Comment by ZhengPeng7** [comment]
是的, 没有npy的吧, 我的google-drive上有, 你可以[下一下看看](https://drive.google.com/file/d/1-BYf8oj30LF_55fpow6eo3yD5n0h3DTE/view?usp=drive_link).
