### ISSUE TITLE
关于RefUnet(nn.Module)模块的问题

### ISSUE THREAD

**Issue by cuihaojie-plus** [ZhengPeng7/GCoNet_plus#7]
想知道RefUnet(nn.Module)模块的作用是什么，在论文中有对应的部分吗？

如能回答，万分感谢！

祝好~

**Comment by ZhengPeng7** [comment]
论文中没有用到, 是参考了[BASNet](https://openaccess.thecvf.com/content_CVPR_2019/papers/Qin_BASNet_Boundary-Aware_Salient_Object_Detection_CVPR_2019_paper.pdf)的refine模块做的尝试, 不过几种方式在这里都没有什么效果.

**Comment by cuihaojie-plus** [comment]
嗯嗯好的，感谢~
想再问一个问题……（麻烦啦）
想问下文中的cls_mask对应的时文中的RACM模块吗？
<img width="456" alt="image" src="https://user-images.githubusercontent.com/69131051/206649692-e49d864f-47cf-4dc1-82d2-094c3bbe4607.png">

**Comment by cuihaojie-plus** [comment]
还想问下这个loss_sal_layers和loss_cls_mask_last_layers的值的设定有什么规则和内涵么？
<img width="490" alt="image" src="https://user-images.githubusercontent.com/69131051/206654425-278b3911-b6b2-48f3-a3ae-964ae8e700c8.png">

**Comment by ZhengPeng7** [comment]
是的, 就是对应的. 然后后面那个是想像GICD/GCoNet在dec不同的stage设置supervision. 但是也是效果有负, 所以就去掉了. 这代码里有的部分, 如果没有用到的/和paper无关的, 就自行去看看吧, 因为有的尝试后丢弃的内容比较多, 你如果觉得可能有用也可以开启或自行修改.

**Comment by cuihaojie-plus** [comment]
> 是的, 就是对应的. 然后后面那个是想像GICD/GCoNet在dec不同的stage设置supervision. 但是也是效果有负, 所以就去掉了. 这代码里有的部分, 如果没有用到的/和paper无关的, 就自行去看看吧, 因为有的尝试后丢弃的内容比较多, 你如果觉得可能有用也可以开启或自行修改.

好的，感谢回复~
