### ISSUE TITLE
Class_Activation_Mapping

### ISSUE THREAD

**Issue by ChenHuyoo** [ZhengPeng7/GCoNet_plus#8]
您好！请问可以提供类激活图可视化代码吗？

**Comment by ZhengPeng7** [comment]
当然, 但是是在单独的repo里改的, 和main的repo比可能有些滞后, 我半小时整合一下.

**Comment by ChenHuyoo** [comment]
好的，谢谢您

**Comment by ZhengPeng7** [comment]
Hi, I have added the notebooks for the visualizations of CAM and FPN. You can have a try on those now.
Other existing codes were not affected.

**Comment by ChenHuyoo** [comment]
Well, thanks very much for your help.---- Replied Message ----FromPeng ***@***.***>Date07/05/2023 02:25 ***@***.***> ***@***.***>***@***.***>SubjectRe: [ZhengPeng7/GCoNet_plus] Class_Activation_Mapping (Issue #8)
Hi, I have added the notebooks for the visualizations of CAM and FPN. You can have a try on those now.
Other existing codes were not affected.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ZhengPeng7/GCoNet_plus/issues/8#issuecomment-1620605167",
"url": "https://github.com/ZhengPeng7/GCoNet_plus/issues/8#issuecomment-1620605167",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
