### ISSUE TITLE
cocoseg数据集问题

### ISSUE THREAD

**Issue by zhiwang98** [ZhengPeng7/GCoNet_plus#9]

**Comment by zhiwang98** [comment]
请问cocoseg数据集你是怎么处理的，我记得有个npy文件

**Comment by ZhengPeng7** [comment]
Please refer to https://github.com/ZhengPeng7/GCoNet_plus/issues/4#issuecomment-1729239173.

**Comment by zhiwang98** [comment]
谢谢作者的回答，但是那个cocoseg为什么我显示无法下载，是文件太大了嘛。那个cocoseg和coco数据集有什么关系，我记得cocoseg也就两万张照片，为什么数据集这么大

**Comment by ZhengPeng7** [comment]
coco-9k或者叫coco-9213是9213个样本对, img+gt接近两万张. coco-seg很大的, ~200k对样本.
我这里是把coco-seg.zip依类别分为[好几个更小的文件](https://drive.google.com/drive/folders/1PpoAi-XZJft0-AKI2qoXrTYqTrKigqtV?usp=drive_link), 你可能会更好下.
你也可以从百度网盘[下载](https://pan.baidu.com/s/1BJp1kFDDZsHq4vg9W7jzYg) (pw: CCSG).

**Comment by zhiwang98** [comment]
非常感谢
